"""fixed_balance_and_raw_change_state

Revision ID: df819c4f84d6
Revises: fa97866f75da
Create Date: 2025-12-11 15:10:10.173786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df819c4f84d6"
down_revision: Union[str, Sequence[str], None] = "fa97866f75da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удалить все данные, тк изменились статусы
    balance_changes = sa.table("balance_changes")
    op.execute(balance_changes.delete())

    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("accounts", sa.Column("balance", sa.Float(), nullable=False))
    op.add_column(
        "accounts",
        sa.Column(
            "is_balance_fixed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # op.drop_column("accounts", "current_balance")
    op.execute("ALTER TABLE accounts RENAME COLUMN current_balance TO balance")
    op.add_column(
        "balance_changes", sa.Column("state_raw", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("balance_changes", "state_raw")
    # op.add_column(
    #     "accounts",
    #     sa.Column(
    #         "current_balance",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    # )
    op.drop_column("accounts", "is_balance_fixed")
    # op.drop_column("accounts", "balance")
    op.execute("ALTER TABLE accounts RENAME COLUMN balance TO current_balance")
    # ### end Alembic commands ###
