"""balance_diff

Revision ID: 97612310611f
Revises: 12640102aaf8
Create Date: 2025-11-24 17:26:35.113818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97612310611f'
down_revision: Union[str, Sequence[str], None] = '12640102aaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_changes', sa.Column('balance_diff', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_changes', 'balance_diff')
    # ### end Alembic commands ###
