"""balance_change

Revision ID: 6d48b9e7aba4
Revises: eca00f9a9181
Create Date: 2025-11-20 17:51:26.683475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d48b9e7aba4'
down_revision: Union[str, Sequence[str], None] = 'eca00f9a9181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_changes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_changes'))
    )
    op.create_index(op.f('ix_balance_changes_id'), 'balance_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_changes_id'), table_name='balance_changes')
    op.drop_table('balance_changes')
    # ### end Alembic commands ###
